import './css/styles.css'
import AuthContext from "./auth/AuthContext"
import QueryWrapper from "./QueryWrapper"
import Nav from "./Nav"

export const metadata = {
  title: 'Talk It Through',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet"/>
      </head>
      <body>
        <QueryWrapper>
          <AuthContext>
            <Nav/>
            {children}
          </AuthContext>
        </QueryWrapper>
      </body>
    </html>
  )
}
